### ISSUE TITLE
Rotate Marker icon as per direction

### ISSUE THREAD

**Issue by harshit13mehta** [ManpreetSingh80/travel-marker#1]
Hi,
How do I rotate the marker icon to show the direction in which the vehicle is moving?
Thanks.

**Comment by ManpreetSingh80** [comment]
Hi harshit,

For simple marker-
If you are using [Symbol](https://developers.google.com/maps/documentation/javascript/reference/3/#Symbol) for marker icon, then you can change rotation value in MarkerOptions using setMarkerOptions method otherwise for png images, you need to have different images with different rotations.

For overlay markers,
Markers rotate by default to show direction like uber. If you need more rotation, you can change offsetAngle in overlayOptions.
